version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pnb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w8pc398kn3fn"
s3_prefix = "pnb"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "pnb-payment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w8pc398kn3fn"
s3_prefix = "pnb-payment"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
