AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pnbpayment

  Sample SAM Template for pnbpayment

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 500

Resources:
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: packages
      Description: Dependencies for the app.
      ContentUri: package/.
      CompatibleRuntimes: 
        - python3.9

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref libs
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  PnBGetQRcodeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pnbqrcodepay/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref libs
      Events:
        qrcodepay:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pnbqrcodepay
            Method: post

  pnbevent:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pnbevent/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Layers:
        - !Ref libs

      Events:
        updateAnEvent:
          Type: Api
          Properties:
            Path: /pnbupdateevent
            Method: post
        getAnEventInfo:
          Type: Api
          Properties:
            Path: /pnbgetevent
            Method: post
        getAllEventInfo:
          Type: Api
          Properties:
            Path: /pnbgetevents
            Method: get

